#!/usr/bin/env python3
"""Collect user like/dislike feedback for digest results."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def _parse_indices(raw: str) -> list[int]:
    picks: list[int] = []
    for part in re.split(r"[,，\s]+", raw.strip()):
        if not part:
            continue
        try:
            idx = int(part)
        except Exception:
            continue
        if idx > 0:
            picks.append(idx)
    return list(dict.fromkeys(picks))


def parse_feedback_text(text: str) -> list[dict[str, Any]]:
    chunks = [x.strip() for x in re.split(r"[;\n\r；]+", text or "") if x.strip()]
    actions: list[dict[str, Any]] = []
    for chunk in chunks:
        label = ""
        payload = ""
        low = chunk.lower()
        if low.startswith("like:"):
            label = "like"
            payload = chunk.split(":", 1)[1].strip()
        elif low.startswith("dislike:"):
            label = "dislike"
            payload = chunk.split(":", 1)[1].strip()
        elif chunk.startswith("+"):
            label = "like"
            payload = chunk[1:].strip()
        elif chunk.startswith("-"):
            label = "dislike"
            payload = chunk[1:].strip()
        else:
            raise ValueError(
                "Invalid feedback segment. Use '+ 1,3' / '- 2#reason' / 'like:1,3; dislike:2#reason'."
            )

        reason = ""
        ids_raw = payload
        if "#" in payload:
            ids_raw, reason = payload.split("#", 1)
            ids_raw = ids_raw.strip()
            reason = reason.strip()
        else:
            # Support: "- 2 太泛"
            m = re.match(r"^([0-9,\s，]+)\s+(.+)$", payload)
            if m:
                ids_raw = m.group(1).strip()
                reason = m.group(2).strip()
        indices = _parse_indices(ids_raw)
        if not indices:
            raise ValueError(f"No valid rank index found in segment: {chunk}")
        actions.append({"label": label, "indices": indices, "reason": reason})
    return actions


def _extract_subscriptions(data: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    if isinstance(data.get("subscriptions"), list):
        for item in data.get("subscriptions", []):
            if not isinstance(item, dict):
                continue
            sub = str(item.get("subscription", "")).strip() or "digest"
            papers = item.get("papers", [])
            if isinstance(papers, list):
                out[sub] = papers
    if not out and isinstance(data.get("results"), list):
        for item in data.get("results", []):
            if not isinstance(item, dict):
                continue
            sub = str(item.get("subscription", "")).strip() or "digest"
            papers = item.get("selected_papers", [])
            if isinstance(papers, list):
                out[sub] = papers
    return out


def select_subscription(
    subscriptions: dict[str, list[dict[str, Any]]],
    preferred: str,
) -> tuple[str, list[dict[str, Any]]]:
    if not subscriptions:
        raise ValueError("No subscription paper list found in selection file.")

    if preferred:
        for k, papers in subscriptions.items():
            if k == preferred or k.lower() == preferred.lower():
                return k, papers
        names = ", ".join(subscriptions.keys())
        raise ValueError(f"Subscription '{preferred}' not found. Available: {names}")

    if len(subscriptions) == 1:
        k = next(iter(subscriptions.keys()))
        return k, subscriptions[k]

    names = ", ".join(subscriptions.keys())
    raise ValueError(f"Multiple subscriptions found. Please specify --subscription. Available: {names}")


def append_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Collect digest feedback by rank index")
    parser.add_argument(
        "--selection-file",
        default="data/feedback/last_selection.json",
        help="Selection map generated by run_digest.py",
    )
    parser.add_argument("--subscription", default="", help="Subscription name/id. Required when multiple subscriptions exist")
    parser.add_argument(
        "--feedback",
        required=True,
        help="Examples: '+ 1,3; - 2#太泛' or 'like:1,3; dislike:2#太偏NLP'",
    )
    parser.add_argument("--output", default="data/feedback/feedback.jsonl")
    parser.add_argument("--actor", default="user", help="Feedback actor label")
    args = parser.parse_args()

    selection_path = Path(args.selection_file)
    if not selection_path.exists():
        raise FileNotFoundError(f"Selection file not found: {selection_path}")
    data = load_json(selection_path)
    subscriptions = _extract_subscriptions(data if isinstance(data, dict) else {})
    sub_name, papers = select_subscription(subscriptions, args.subscription.strip())

    by_rank: dict[int, dict[str, Any]] = {}
    for i, p in enumerate(papers, start=1):
        if not isinstance(p, dict):
            continue
        rank = p.get("rank", i)
        try:
            rank = int(rank)
        except Exception:
            rank = i
        if rank > 0:
            by_rank[rank] = p

    actions = parse_feedback_text(args.feedback)
    now = datetime.now(timezone.utc).isoformat()
    rows: list[dict[str, Any]] = []
    skipped: list[int] = []
    for action in actions:
        label = action["label"]
        reason = str(action.get("reason", "")).strip()
        for idx in action["indices"]:
            paper = by_rank.get(idx)
            if not paper:
                skipped.append(idx)
                continue
            rows.append(
                {
                    "ts_utc": now,
                    "actor": args.actor,
                    "subscription": sub_name,
                    "label": label,
                    "reason": reason,
                    "rank": idx,
                    "feedback_id": str(paper.get("feedback_id", "")).strip(),
                    "arxiv_id": str(paper.get("arxiv_id", "")).strip(),
                    "version": str(paper.get("version", "")).strip(),
                    "source_field": str(paper.get("source_field", "")).strip(),
                    "title_en": str(paper.get("title_en", "")).strip(),
                    "url": str(paper.get("url", "")).strip(),
                }
            )

    if not rows:
        raise ValueError("No valid feedback records generated.")

    output_path = Path(args.output)
    append_jsonl(output_path, rows)
    print(f"[OK] feedback records appended: {len(rows)} -> {output_path}")
    if skipped:
        print(f"[WARN] skipped unknown rank index: {sorted(set(skipped))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
